services:
  dev:
    build:
      context: .
    container_name: dask
    volumes:
      - ./data:/data
      # prevents container rebuild when src changes
      - ./app:/app 
      - ./vis:/vis
    stdin_open: true